FROM node:18-alpine
WORKDIR /app

RUN npm install -g pm2

COPY package*.json ./
RUN npm install --production
COPY . .

EXPOSE 3050

CMD ["pm2-runtime", "ecosystem.config.js", "--only", "psych-worker", "--env", "production"]
