apiVersion: v1
kind: Service
metadata:
  name: psych-api
  namespace: psych
  labels:
    monitor: "true"   # 👈 REQUIRED
spec:
  selector:
    app: psych-api
  ports:
    - name: http      # 👈 REQUIRED
      port: 80
      targetPort: 3010