name: Sync main with frontend & backend

on:
  push:
    branches:
      - frontend
      - backend

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync branch
        run: |
          BRANCH=$(echo "${GITHUB_REF#refs/heads/}")
          git fetch origin main || true
          git checkout main || git checkout -b main
          git merge origin/$BRANCH --no-edit || true
          git push origin main
